### ISSUE TITLE
slight differences in predict_proba vs cpp

### ISSUE THREAD

**Issue by niklasnolte** [bixel/bdt2cpp#3]
evaluating a xgb classifier in python gives me slightly different results than running the cpp version.
they are in the % level, but still strange. is this expected?

**Comment by niklasnolte** [comment]
its probably because predict_proba and the sigmoid you provide yield different results, right?

**Comment by bixel** [comment]
They should be below %. Maybe recent XGBoost versions have changed things slightly.

**Comment by bixel** [comment]
I'll close this now. [treelite](https://github.com/dmlc/treelite) seems to have evolved in parallel, but with some more brain-power behind it ;)
